pipeline {
    agent {
        node { label 'node1' }
    }
    environment {
        packageVersion = ''
        //nexusURL = credentials('nexusURL')
        environment = 'dev'
    }
    options {
        ansiColor('xterm') //ansiColor plugin
    }
    parameters {
        string(name:'nexusURL', defaultValue: '')
    }
    stages {
        stage('Get the version') {
            steps {
                sh '''
                    ls -la
                    cd catalogue
                    ls -la
                '''
                script { //Pipeline utility steps plugin
                    def packageJson = readJSON file: 'catalogue/package.json'
                    packageVersion = packageJson.version
                    echo "Application version: $packageVersion"
                }
            }
        }
        stage('Install dependencies') {
            steps {     //Install nodejs in agent/node
                sh '''
                    cd catalogue
                    ls -la
                    npm install
                '''
            }
        }
        stage('Build') {
            steps {
                sh '''
                    cd catalogue
                    ls -la
                    zip -q -r catalogue.zip ./* -x ".git" -x "*.zip"
                    ls -ltr
                ''' 
            }
        }
        stage('upload artifact') { //Nexus Artifact Uploader plugin
            steps {
                nexusArtifactUploader(
                    nexusVersion: 'nexus3',
                    protocol: 'http',
                    //nexusUrl: "${env.nexusURL}",
                    nexusUrl: "${params.nexusURL}",
                    groupId: 'com.robotshop',
                    version: "${packageVersion}", //Updates nexus repository with new sematic version
                    repository: 'catalogue',
                    credentialsId: 'nexus-auth', //Congifure inside manage credentials section
                    artifacts: [
                        [artifactId: 'catalogue',
                        classifier: '',
                        file: 'catalogue/catalogue.zip',
                        type: 'zip']
                    ]
                )
            }
        }
        stage('Trigger-deploy-job') {
            steps {
                script {
                    def params = [
                        string(name: 'version', value: "${packageVersion}"),
                        string(name: 'environment', value: "${environment}")
                    ]
                    build job: "catalogue-deploy", wait: true, parameters:params //triggers catalogue-deploy job
                }
            }
        }
    }
    post {
        always {
            echo "Deleting directory"
            deleteDir()
        }
    }
}